### ISSUE TITLE
New Customfont "core" version doesn't work

### ISSUE THREAD

**Issue by Gamesnic** [Tomrdh/discord-addons#5]
It simply doesn't work, not any fonts gets set.
Why don't you just let nifn be it just works well

![image](https://user-images.githubusercontent.com/49643487/107922390-3cae2c80-6f70-11eb-9dd3-bbd5177af1a2.png)

**Comment by Tomrdh** [comment]
I responded to you on Discord, I'll close the issue here and I am waiting for more details
